theme: jekyll-theme-slate
site_favicon: assets/icons/favicon.ico
title: Clopen Mic Night

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "winter"
